[package]
name = "qr-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
qrcode = "0.12"

[dev-dependencies]
tempfile = "3.23.0"

[[bin]]
name = "qr-generator"
path = "src/main.rs"